# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95deab681d720483325bc9d251ae9a5f9a439040f015ba40ff6d70651bff3eca084cf836c63189e3d838cccf1d1c5483a6eea8a0bd67c7bedd3429e6ccb5e866

test:
  secret_key_base: 026f85cd29b2bce3095fc8ca16c42afd33df0d528902537576d4c4bf9251574bb7e52e17282621a4245dd60f17a084eb2c156a016c10fc058292aa17f709e543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
